const fs = require('fs');
const file = 'C:/Users/zsomb/Documents/melogo_app/scratch/melogo/frontend/index.html';
let content = fs.readFileSync(file, 'utf8');

// Ensure we remove the dark mode class from body/html
content = content.replace(/apple-premium-dark-mode/g, 'apple-premium-light-mode');

// Remove any previously injected style blocks to start fresh
content = content.replace(/<style id="lava-glow">[\s\S]*?<\/style>/g, '');
content = content.replace(/<style id="ultimate-light[^>]*>[\s\S]*?<\/style>/g, '');
content = content.replace(/<style id="aggressive-light">[\s\S]*?<\/style>/g, '');
content = content.replace(/<style id="light-orange-glow">[\s\S]*?<\/style>/g, '');

const lightGrayStyle = `
<style id="light-gray-orange-glow">
    /* 1. Sötét Mód letiltása & 2. Inkább szürkés háttér */
    :root, html, body, #app-container, .apple-premium-light-mode {
        --color-bg: #DCDCE0 !important; /* Inkább szürkés háttér */
        --color-surface: rgba(255, 255, 255, 0.6) !important;
        --color-text: #1C1C1E !important; /* Sötét szöveg */
        --color-text-muted: #636366 !important;
        --color-border: rgba(0, 0, 0, 0.1) !important;
        --color-green: #FF5722 !important; /* Láva narancs kiemelések */
        background-color: #DCDCE0 !important;
        color: #1C1C1E !important;
    }

    /* 3. Fentről lefelé sugárzó narancs színátmenet */
    body, #app-container {
        background: radial-gradient(150% 50% at 50% 0%, rgba(255, 87, 34, 0.3) 0%, rgba(255, 140, 0, 0.05) 40%, #DCDCE0 100%) !important;
        background-attachment: fixed !important;
        min-height: 100vh;
    }
    
    * {
        color: inherit;
    }

    /* Szövegek sötétítése */
    .brand-logo, .welcome-text, h2, p {
        color: #1C1C1E !important;
    }

    /* 4. "Go" logó visszaállítása Neon Zöldre, sötét árnyékkal */
    .brand-logo span {
        color: #c0fc2a !important; /* Neon Go */
        text-shadow: 0px 1px 3px rgba(0, 0, 0, 0.5) !important;
    }

    /* Keresőmező */
    .header-midnight, #home-search-display, .search-bar, .gps-bar {
        background: transparent !important;
    }
    #home-search-display {
        color: #1C1C1E !important;
    }
    #home-search-display::placeholder {
        color: #636366 !important;
    }

    /* GPS és Távolság feliratok */
    .gps-location, .distance-pill-btn, .gps-location span, .distance-pill-btn span {
        color: #636366 !important;
    }
    #gps-city-label, #distance-pill-text {
        color: #1C1C1E !important;
    }
    
    /* Munkakártyák */
    .job-card {
        background: rgba(255, 255, 255, 0.5) !important;
        backdrop-filter: blur(10px);
        -webkit-backdrop-filter: blur(10px);
        border-bottom: 0.5px solid rgba(0, 0, 0, 0.1) !important;
    }
    
    .job-title {
        color: #1C1C1E !important;
    }
    .job-price {
        color: #FF5722 !important; /* Narancs ár */
    }
    .job-card-badges span {
        color: #636366 !important;
    }

    /* 5. Kiválasztott menük narancssárgára színezése */
    .category-btn, div[onclick^="setDateFilter"] {
        color: #636366 !important;
    }
    
    /* Dátum napok (7, 8, 9) és aktív állapotok */
    #date-filter-row span:nth-child(1) { color: #636366 !important; }
    #date-filter-row span:nth-child(2) { color: #1C1C1E !important; font-weight: 500 !important; }
    
    /* Aktív kategória gombok */
    .category-btn.active, div[onclick^="setDateFilter"][style*="1px solid"] {
        color: #FF5722 !important;
        border-bottom-color: #FF5722 !important;
    }
    
    /* Kiemelt "Minden", "Kertészet" szűrők, amiknek keretük volt - ezek is legyenek narancsok aktívként */
    .filter-pill, .employer-pill, .sort-pill, .msg-filter-pill { color: #636366 !important; }
    .filter-pill.active, .employer-pill.active { color: #FF5722 !important; border-bottom: 1px solid #FF5722 !important; }

    /* Alsó navigáció */
    .bottom-nav {
        background: rgba(230, 230, 235, 0.9) !important;
        border-top: 1px solid rgba(0, 0, 0, 0.05) !important;
    }
    .nav-item {
        color: #636366 !important;
    }
    .nav-item.active {
        color: #FF5722 !important;
    }
    
    svg { stroke: currentColor; }
    .MuiSvgIcon-root { fill: none !important; }
</style>
</head>`;

content = content.replace(/<\/head>/, lightGrayStyle);

// Overwrite inline white text colors generated by JS just in case
const fixWhite = `
    /* Fix inline white colors generated by JS */
    span[style*="color: #FFFFFF"] { color: inherit !important; }
    span[style*="color: #FFF"] { color: inherit !important; }
    span[style*="color: #ffffff"] { color: inherit !important; }
`;
if (!content.includes('span[style*="color: #FFFFFF"]')) {
    content = content.replace(/<\/style>\s*<\/head>/, fixWhite + '</style>\n</head>');
}

fs.writeFileSync(file, content, 'utf8');
console.log('Light Gray + Orange Glow applied!');
