const fs = require('fs');
const file = 'C:/Users/zsomb/Documents/melogo_app/scratch/melogo/frontend/index.html';
let content = fs.readFileSync(file, 'utf8');

const fixEmployerCSS = `
    /* Fix employer and badges white colors */
    .employer-name, .job-employer, .job-badge-cat, .job-badge-urgent, .job-badge-loc, .job-badge-time { color: #636366 !important; }
    .job-card span, .job-card div { color: inherit; }
    .employer-name { color: #636366 !important; }
    .job-card p { color: #1C1C1E !important; }
`;

content = content.replace(/\/\* Fix inline white colors generated by JS \*\//, `/* Fix inline white colors generated by JS */\n${fixEmployerCSS}`);

fs.writeFileSync(file, content, 'utf8');
console.log('Fixed job card text colors!');
