const fs = require('fs');
const file = 'C:/Users/zsomb/Documents/melogo_app/scratch/melogo/frontend/index.html';
let content = fs.readFileSync(file, 'utf8');

const fixWhite = `
    #date-filter-row span, .bottom-nav svg, .welcome-text, .MuiSvgIcon-root { color: #111111 !important; stroke: #111111 !important; fill: none !important; }
    .bottom-nav .active svg { stroke: #FF5722 !important; }
    .filter-pill, .employer-pill, .sort-pill, .msg-filter-pill { color: #666666 !important; }
    .filter-pill.active, .employer-pill.active { color: #111111 !important; border-bottom: 1px solid #111111 !important; }
    /* Fix inline white colors generated by JS */
    span[style*="color: #FFFFFF"] { color: inherit !important; }
    span[style*="color: #FFF"] { color: inherit !important; }
`;

content = content.replace(/<\/style>\s*<\/head>/, fixWhite + '</style>\n</head>');
fs.writeFileSync(file, content, 'utf8');
console.log('Fixed white inline text');
